void DetectFW();
void DetectCN();
void DetectID();
void MainCRC(void* lpParam);
void DetectSBP();
void DetectHBP();
void DetectBD();
void DetectNtQSI();
void SplashShow();
void AntiPE();
void DetectMemory();
void DetectCRDP();
void SelfDebug();
void DetectNtSIT();